-- Drop tables if they already exist
DROP TABLE IF EXISTS public.todos CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;

-- Create todos table
CREATE TABLE public.todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_complete boolean DEFAULT false NOT NULL,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create products table
CREATE TABLE public.products (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  part_number text NOT NULL UNIQUE,
  title text NOT NULL,
  category text NOT NULL,
  price numeric NOT NULL,
  stock integer DEFAULT 0 NOT NULL,
  description text,
  gradient_class text,
  specs jsonb DEFAULT '{}'::jsonb NOT NULL,
  bulk_pricing jsonb DEFAULT '[]'::jsonb NOT NULL,
  datasheet_url text,
  cad_file text,
  extended_specs jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create services table
CREATE TABLE public.services (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL,
  description text,
  base_price numeric NOT NULL,
  lead_time text NOT NULL,
  features jsonb DEFAULT '[]'::jsonb NOT NULL,
  gradient_class text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- Grant public read access
CREATE POLICY "Allow public read-only access for todos" ON public.todos FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read-only access for products" ON public.products FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read-only access for services" ON public.services FOR SELECT TO anon, authenticated USING (true);

-- Allow public insert/update for todos to support user checklist actions
CREATE POLICY "Allow public insert for todos" ON public.todos FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update for todos" ON public.todos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

-- Seed todos
INSERT INTO public.todos (name, is_complete) VALUES
('Initialize database with schema', true),
('Verify RLS policies on tables', true),
('Seed 10 mechatronic products', false),
('Seed 5 manufacturing services', false),
('Verify frontend fetches from Supabase', false);

-- Seed products (10 mechatronics products)
INSERT INTO public.products (part_number, title, category, price, stock, description, gradient_class, specs, bulk_pricing, datasheet_url, cad_file, extended_specs) VALUES
(
  'ACT-NEMA23-CL',
  'NEMA 23 Closed-Loop Stepper Motor',
  'Actuators',
  189.50,
  45,
  'High-torque closed-loop hybrid stepper motor with integrated encoder. Eliminates missed steps and provides real-time position feedback.',
  'from-cobalt/20 to-cobalt/5 border-cobalt/20',
  '{"Holding Torque": "2.2 N.m", "Encoder Resolution": "1000 CPR", "Frame Size": "NEMA 23 (57mm)", "Shaft Diameter": "8mm"}',
  '[{"minQty": 1, "pricePerUnit": 189.50}, {"minQty": 5, "pricePerUnit": 175.00}, {"minQty": 20, "pricePerUnit": 158.00}]',
  'https://datasheet.mechitall.io/ACT-NEMA23-CL.pdf',
  'ACT-NEMA23-CL.step',
  '{"dimensions": "57mm x 57mm x 104mm", "temperatureRange": "-20C to +50C", "mtbf": "25,000 Hours", "ingressProtection": "IP54", "electricalRating": "4.2A, 24-50VDC"}'
),
(
  'ACT-LIN-12V100',
  'High-Force Linear Actuator (100mm)',
  'Actuators',
  125.00,
  30,
  '12V DC linear actuator with 100mm stroke length. Heavy duty metal gears with built-in limit switches for safety.',
  'from-cobalt/20 to-cobalt/5 border-cobalt/20',
  '{"Stroke Length": "100mm", "Max Load Force": "750 N", "Speed (No Load)": "10 mm/s", "Voltage": "12 VDC"}',
  '[{"minQty": 1, "pricePerUnit": 125.00}, {"minQty": 10, "pricePerUnit": 112.50}]',
  'https://datasheet.mechitall.io/ACT-LIN-12V100.pdf',
  'ACT-LIN-12V100.step',
  '{"dimensions": "215mm x 40mm x 75mm", "temperatureRange": "-26C to +65C", "mtbf": "15,000 Cycles", "ingressProtection": "IP65", "electricalRating": "12VDC, 3A max"}'
),
(
  'SEN-LIDAR-20M',
  'LiDAR Distance Sensor (20m)',
  'Sensors',
  310.00,
  18,
  'Time-of-flight (ToF) industrial LiDAR distance sensor. Measures up to 20 meters with millimeter precision under various lighting conditions.',
  'from-emerald/20 to-emerald/5 border-emerald/20',
  '{"Measurement Range": "0.1m - 20m", "Accuracy": "+/- 5mm", "Interface": "UART / CAN Bus", "Update Rate": "100 Hz"}',
  '[{"minQty": 1, "pricePerUnit": 310.00}, {"minQty": 5, "pricePerUnit": 290.00}, {"minQty": 10, "pricePerUnit": 270.00}]',
  'https://datasheet.mechitall.io/SEN-LIDAR-20M.pdf',
  'SEN-LIDAR-20M.step',
  '{"dimensions": "50mm x 43mm x 35mm", "temperatureRange": "-10C to +60C", "mtbf": "50,000 Hours", "ingressProtection": "IP67", "electricalRating": "5VDC, 180mA"}'
),
(
  'SEN-IMU-6AXIS',
  'Industrial 6-Axis IMU (CAN Bus)',
  'Sensors',
  98.00,
  120,
  'Ruggedized 6-axis Inertial Measurement Unit containing a 3-axis accelerometer and a 3-axis gyroscope. Factory-calibrated drift compensation.',
  'from-emerald/20 to-emerald/5 border-emerald/20',
  '{"Gyroscope Range": "+/- 2000 dps", "Accelerometer Range": "+/- 16g", "Protocol": "CANopen / J1939", "Operating Current": "15mA"}',
  '[{"minQty": 1, "pricePerUnit": 98.00}, {"minQty": 10, "pricePerUnit": 88.00}, {"minQty": 50, "pricePerUnit": 79.00}]',
  'https://datasheet.mechitall.io/SEN-IMU-6AXIS.pdf',
  'SEN-IMU-6AXIS.step',
  '{"dimensions": "36mm x 36mm x 15mm", "temperatureRange": "-40C to +85C", "mtbf": "100,000 Hours", "ingressProtection": "IP67", "electricalRating": "9-36VDC, 0.5W"}'
),
(
  'BRD-STM32-M4',
  'STM32 Mechatronics Controller Board',
  'Control Boards',
  145.00,
  55,
  'Advanced development board tailored for robotics and motion control. Features rich communication interfaces and motor driver outputs.',
  'from-amber-500/20 to-amber-500/5 border-amber-500/20',
  '{"MCU": "STM32F407VGT6", "Clock Speed": "168 MHz", "Motor Output": "4x H-Bridge channels", "Connectivity": "CAN, SPI, I2C, USB, UART"}',
  '[{"minQty": 1, "pricePerUnit": 145.00}, {"minQty": 5, "pricePerUnit": 135.00}, {"minQty": 20, "pricePerUnit": 120.00}]',
  'https://datasheet.mechitall.io/BRD-STM32-M4.pdf',
  'BRD-STM32-M4.step',
  '{"dimensions": "100mm x 80mm x 12mm", "temperatureRange": "-40C to +85C", "mtbf": "80,000 Hours", "ingressProtection": "IP20", "electricalRating": "12-24VDC Input"}'
),
(
  'BRD-BLDC-ESC',
  '4-Channel Brushless Motor Driver',
  'Control Boards',
  215.00,
  24,
  'Four-channel high-power brushless motor electronic speed controller. Supports field-oriented control (FOC) for silent and efficient movement.',
  'from-amber-500/20 to-amber-500/5 border-amber-500/20',
  '{"Continuous Current": "4x 45A", "Peak Current": "4x 60A", "Control Mode": "FOC (Field Oriented Control)", "Telemetry": "Current, Temp, RPM"}',
  '[{"minQty": 1, "pricePerUnit": 215.00}, {"minQty": 10, "pricePerUnit": 195.00}]',
  'https://datasheet.mechitall.io/BRD-BLDC-ESC.pdf',
  'BRD-BLDC-ESC.step',
  '{"dimensions": "65mm x 65mm x 8mm", "temperatureRange": "-10C to +80C", "mtbf": "45,000 Hours", "ingressProtection": "IP30", "electricalRating": "3S-6S LiPo, 12-26V"}'
),
(
  'MCH-PLAN-10',
  'Planetary Gearbox (10:1 NEMA 23)',
  'Mechanical',
  85.00,
  70,
  'High-precision planetary gear reduction box for NEMA 23 motors. Backlash rating under 15 arc-minutes.',
  'from-coral/20 to-coral/5 border-coral/20',
  '{"Reduction Ratio": "10:1", "Max Output Torque": "35 N.m", "Backlash": "< 15 arc-min", "Input Speed": "3000 RPM max"}',
  '[{"minQty": 1, "pricePerUnit": 85.00}, {"minQty": 10, "pricePerUnit": 76.50}, {"minQty": 50, "pricePerUnit": 68.00}]',
  'https://datasheet.mechitall.io/MCH-PLAN-10.pdf',
  'MCH-PLAN-10.step',
  '{"dimensions": "57mm x 57mm x 68mm", "temperatureRange": "-15C to +90C", "mtbf": "20,000 Hours", "ingressProtection": "IP54", "electricalRating": "N/A (Mechanical)"}'
),
(
  'MCH-RAIL-C500',
  'Carbon Fiber Linear Guide Rail (500mm)',
  'Mechanical',
  160.00,
  40,
  'Ultra-light carbon fiber composite linear guide rail with steel running tracks. High rigidity and minimal thermal expansion.',
  'from-coral/20 to-coral/5 border-coral/20',
  '{"Length": "500mm", "Material": "Carbon Fiber / Steel", "Rail Width": "15mm", "Dynamic Load Rating": "8.5 kN"}',
  '[{"minQty": 1, "pricePerUnit": 160.00}, {"minQty": 5, "pricePerUnit": 148.00}, {"minQty": 20, "pricePerUnit": 135.00}]',
  'https://datasheet.mechitall.io/MCH-RAIL-C500.pdf',
  'MCH-RAIL-C500.step',
  '{"dimensions": "500mm x 15mm x 10mm", "temperatureRange": "-30C to +120C", "mtbf": "100,000 Meters Travel", "ingressProtection": "N/A (Open)", "electricalRating": "N/A"}'
),
(
  'SEN-ULTR-IP67',
  'Ultrasonic Level Transmitter (IP67)',
  'Sensors',
  175.00,
  35,
  'Non-contact ultrasonic level sensor for liquids and bulk materials. Features an IP67 chemical-resistant PVDF housing.',
  'from-emerald/20 to-emerald/5 border-emerald/20',
  '{"Beam Angle": "8 degrees", "Measuring Distance": "0.3m - 6m", "Output Signal": "4-20mA / Modbus RTU", "Resolution": "1mm"}',
  '[{"minQty": 1, "pricePerUnit": 175.00}, {"minQty": 5, "pricePerUnit": 162.00}]',
  'https://datasheet.mechitall.io/SEN-ULTR-IP67.pdf',
  'SEN-ULTR-IP67.step',
  '{"dimensions": "78mm Diameter x 108mm Length", "temperatureRange": "-20C to +70C", "mtbf": "60,000 Hours", "ingressProtection": "IP67", "electricalRating": "24VDC, 80mA max"}'
),
(
  'ACT-SERVO-400W',
  'Industrial Brushless Servo Motor (400W)',
  'Actuators',
  420.00,
  12,
  'High-performance 400W AC brushless servo motor. Delivers high speed, exceptional acceleration capabilities, and extreme positioning precision.',
  'from-cobalt/20 to-cobalt/5 border-cobalt/20',
  '{"Rated Power": "400 W", "Rated Torque": "1.27 N.m", "Rated Speed": "3000 RPM", "Encoder Type": "17-bit Absolute Encoder"}',
  '[{"minQty": 1, "pricePerUnit": 420.00}, {"minQty": 5, "pricePerUnit": 395.00}, {"minQty": 10, "pricePerUnit": 370.00}]',
  'https://datasheet.mechitall.io/ACT-SERVO-400W.pdf',
  'ACT-SERVO-400W.step',
  '{"dimensions": "60mm x 60mm x 120mm", "temperatureRange": "0C to +40C", "mtbf": "40,000 Hours", "ingressProtection": "IP65", "electricalRating": "220VAC, 2.5A"}'
);

-- Seed services (5 B2B manufacturing services)
INSERT INTO public.services (title, category, description, base_price, lead_time, features, gradient_class) VALUES
(
  'CNC Milling & Turning',
  'CNC Machining',
  'High-precision subtraction manufacturing on 3-axis and 5-axis CNC machining centers. Suitable for metals and engineered plastics.',
  150.00,
  '10 business days (Standard)',
  '["ISO 9001 certified facilities", "Precision tolerances up to +/- 0.005mm", "Anodizing and bead blasting post-processing", "Supports over 30 metals and plastics"]',
  'from-cobalt/20 to-cobalt/5 border-cobalt/20'
),
(
  'Industrial SLS 3D Printing',
  '3D Printing',
  'Selective Laser Sintering (SLS) of robust functional prototypes. Prints high-durability Nylon 12 parts without support structures.',
  45.00,
  '4 business days (Expedited)',
  '["Excellent structural and mechanical properties", "Ideal for snap-fits, living hinges, and complex geometries", "Batch sorting and bead blast surface smoothing", "Zero support material needed"]',
  'from-emerald/20 to-emerald/5 border-emerald/20'
),
(
  'Sheet Metal Fabrication',
  'Metal Fabrication',
  'Laser cutting, punching, sheet folding, and stamping for rapid production. Perfect for mechatronic enclosures, structural panels, and brackets.',
  95.00,
  '7 business days (Standard)',
  '["Precision laser cutting up to 12mm thickness", "Diverse range of raw materials (AL, Steel, Brass, Copper)", "Powder coating, plating, and silk screening finishes", "Automated CAD design-for-manufacturability validation"]',
  'from-coral/20 to-coral/5 border-coral/20'
),
(
  'Mechatronics System Design',
  'Engineering Consultation',
  '1-on-1 engineering design and system integration consultations. Support for sensor selection, kinematic analysis, custom PCB layouts, and firmware architectures.',
  120.00,
  'As scheduled (Hourly)',
  '["Experienced mechatronic and software engineers", "Kinematic, static stress, and thermal CAD simulations", "PCB schematic reviews and signal integrity analysis", "Firmware code architecture planning"]',
  'from-amber-500/20 to-amber-500/5 border-amber-500/20'
),
(
  'High-Detail SLA Resin Printing',
  '3D Printing',
  'Stereolithography (SLA) laser resin printing. Yields smooth surface finish, ultra-high feature detail, and exact dimensional stability.',
  65.00,
  '3 business days (Expedited)',
  '["Microfluidic and high-tolerance validation parts", "Clear, flexible, and castable specialized resins", "Smooth as-printed finishes suitable for master molds", "Layer thickness down to 25 microns"]',
  'from-emerald/20 to-emerald/5 border-emerald/20'
);

-- =========================================================================
-- NUTS & BOLTS REWARDS SYSTEM SCHEMA UPDATES
-- =========================================================================

-- 1. Create Profiles Table if not exists
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text DEFAULT 'Guest User' NOT NULL,
  wallet_balance integer DEFAULT 0 NOT NULL CHECK (wallet_balance >= 0),
  loyalty_tier text DEFAULT 'Tinkerer' NOT NULL CHECK (loyalty_tier IN ('Tinkerer', 'Master Builder')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id text PRIMARY KEY, -- formats like PO-2026-XXXXX
  profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  total_amount numeric NOT NULL,
  items_count integer NOT NULL,
  status text NOT NULL CHECK (status IN ('Processing', 'Shipped', 'Delivered', 'Completed')),
  unboxing_photo_url text,
  rewards_claimed boolean DEFAULT false NOT NULL,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Bolts Transactions Table
CREATE TABLE IF NOT EXISTS public.bolts_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount integer NOT NULL, -- positive for credits, negative for debits (redemption, expiration)
  type text NOT NULL CHECK (type IN ('credit', 'debit', 'expiration')),
  order_id text REFERENCES public.orders(id) ON DELETE SET NULL,
  description text NOT NULL,
  expires_at timestamp with time zone, -- set only for credits
  is_expired boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Rewards Settings Table (Margin Protection Variables)
CREATE TABLE IF NOT EXISTS public.rewards_settings (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  bolts_per_dollar_spent numeric DEFAULT 1.0 NOT NULL, -- e.g. 1 Bolt earned per ₹1 spent
  exchange_rate_bolts_per_dollar numeric DEFAULT 10.0 NOT NULL, -- 10 Bolts = ₹1.00 store credit value
  max_bolts_per_transaction integer DEFAULT 100 NOT NULL, -- max cap per order
  inspection_window_days integer DEFAULT 7 NOT NULL
);

-- Seed rewards settings if not already present
INSERT INTO public.rewards_settings (id, bolts_per_dollar_spent, exchange_rate_bolts_per_dollar, max_bolts_per_transaction, inspection_window_days)
VALUES (1, 1.0, 10.0, 100, 7)
ON CONFLICT (id) DO NOTHING;

-- 5. Trigger function to automatically upgrade Tinkerer to Master Builder when they hit 500 cumulative/current balance
CREATE OR REPLACE FUNCTION public.check_loyalty_tier_upgrade()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.wallet_balance >= 500 THEN
    NEW.loyalty_tier := 'Master Builder';
  ELSE
    NEW.loyalty_tier := 'Tinkerer';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_upgrade_tier ON public.profiles;
CREATE TRIGGER trigger_upgrade_tier
BEFORE INSERT OR UPDATE OF wallet_balance ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.check_loyalty_tier_upgrade();

-- 6. Expiration logic function
CREATE OR REPLACE FUNCTION public.expire_old_bolts()
RETURNS void AS $$
DECLARE
  rec RECORD;
BEGIN
  -- Loop through unexpired credits that are past their expiration date
  FOR rec IN 
    SELECT id, profile_id, amount 
    FROM public.bolts_transactions 
    WHERE type = 'credit' 
      AND is_expired = false 
      AND expires_at < now()
  LOOP
    -- Mark ledger entry as expired
    UPDATE public.bolts_transactions 
    SET is_expired = true 
    WHERE id = rec.id;

    -- Add expiration debit transaction
    INSERT INTO public.bolts_transactions (profile_id, amount, type, description)
    VALUES (rec.profile_id, -rec.amount, 'expiration', 'Expiration of ' || rec.amount || ' earned Bolts');

    -- Deduct from profile balance
    UPDATE public.profiles
    SET wallet_balance = GREATEST(0, wallet_balance - rec.amount)
    WHERE id = rec.profile_id;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- 7. Enable RLS and Create Policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bolts_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rewards_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read profiles" ON public.profiles;
DROP POLICY IF EXISTS "Allow public insert profiles" ON public.profiles;
DROP POLICY IF EXISTS "Allow public update profiles" ON public.profiles;
CREATE POLICY "Allow public read profiles" ON public.profiles FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert profiles" ON public.profiles FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update profiles" ON public.profiles FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public insert orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public update orders" ON public.orders;
CREATE POLICY "Allow public read orders" ON public.orders FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert orders" ON public.orders FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update orders" ON public.orders FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read transactions" ON public.bolts_transactions;
DROP POLICY IF EXISTS "Allow public insert transactions" ON public.bolts_transactions;
CREATE POLICY "Allow public read transactions" ON public.bolts_transactions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert transactions" ON public.bolts_transactions FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read settings" ON public.rewards_settings;
CREATE POLICY "Allow public read settings" ON public.rewards_settings FOR SELECT TO anon, authenticated USING (true);

